# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assetcap < Formula
  desc "Digital Asset Capitalization Management Tool"
  homepage "https://github.com/helmedeiros/digital-asset-capitalization"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.6.0/assetcap_darwin_amd64.tar.gz"
      sha256 "ba5d62722e345ffdaa506cd67d670e81bc5a2127ef8966de362f16256729eccb"

      def install
        bin.install "assetcap"
      end
    end
    on_arm do
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.6.0/assetcap_darwin_arm64.tar.gz"
      sha256 "be5e79e9d6fc907474c18f7efae727023aa3fe97f1dc546cc5b4c8eec5615177"

      def install
        bin.install "assetcap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.6.0/assetcap_linux_amd64.tar.gz"
        sha256 "3fb63538a82f43ae12347dd340b10df38faca3218873d5352d9a9070f58e4e23"

        def install
          bin.install "assetcap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.6.0/assetcap_linux_arm64.tar.gz"
        sha256 "5c2d630ce7c55f26be7088e147eae2062ec891669aa27d0aa121cfc3e3699f7f"

        def install
          bin.install "assetcap"
        end
      end
    end
  end

  test do
    system "#{bin}/assetcap --help"
  end
end
