# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assetcap < Formula
  desc "Digital Asset Capitalization Management Tool"
  homepage "https://github.com/helmedeiros/digital-asset-capitalization"
  version "1.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.15.0/assetcap_darwin_amd64.tar.gz"
      sha256 "43d6bbd7c8d361a29d13c0bf51c4931c521e52e0e717d8f4304abab2fdd8f41d"

      def install
        bin.install "assetcap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.15.0/assetcap_darwin_arm64.tar.gz"
      sha256 "d3c6e25842706cd393327305500dd8cc99d2aa743534f9d123ab0b9ef92b15bf"

      def install
        bin.install "assetcap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.15.0/assetcap_linux_amd64.tar.gz"
      sha256 "6d22c60bc1aa5dade59815a778ee634ca1a2d92149dafe44409dcd6502a249ff"
      def install
        bin.install "assetcap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helmedeiros/digital-asset-capitalization/releases/download/v1.15.0/assetcap_linux_arm64.tar.gz"
      sha256 "a47cd4f3011a72380b2446e1adec6a923df9b8e026031e2ff99c701d4d27d14a"
      def install
        bin.install "assetcap"
      end
    end
  end

  test do
    system "#{bin}/assetcap --help"
  end
end
